extensions:
    spygar-magento2-credentials-create-modal:
        module: pim/form/common/creation/modal
        config:
            labels:
                title: pim_common.create
                subTitle: pim_menu.item.credentials
            picture: illustrations/Family.svg
            successMessage: spygar_magento2.credentials.flash.create.success
            editRoute: spygar_magento2_edit_credential            
            postUrl: spygar_magento2_create_credential
            entityIdentifierParamName: meta.id

    spygar-magento2-credentials-create-modal-url:
        module: pim/form/common/fields/text
        parent: spygar-magento2-credentials-create-modal
        position: 10
        targetZone: fields
        config:
            fieldName: url
            label: spygar_magento2.credential.url
            required: true
            
    spygar-magento2-credentials-create-modal-access-token:
        module: pim/form/common/fields/text
        parent: spygar-magento2-credentials-create-modal
        position: 15
        targetZone: fields
        config:
            fieldName: access_token
            label: spygar_magento2.credential.access_token
            required: true