extensions:
    spygar-shopify-credentials-create-modal:
        module: pim/form/common/creation/modal
        config:
            labels:
                title: pim_common.create
                subTitle: pim_menu.item.credentials
            picture: illustrations/Family.svg
            successMessage: spygar_shopify.credentials.flash.create.success
            editRoute: spygar_shopify_edit_credential            
            postUrl: spygar_shopify_create_credential
            entityIdentifierParamName: meta.id

    spygar-shopify-credentials-create-modal-url:
        module: pim/form/common/fields/text
        parent: spygar-shopify-credentials-create-modal
        position: 10
        targetZone: fields
        config:
            fieldName: url
            label: spygar_shopify.credential.url
            required: true
            
    spygar-shopify-credentials-create-modal-username:
        module: pim/form/common/fields/text
        parent: spygar-shopify-credentials-create-modal
        position: 15
        targetZone: fields
        config:
            fieldName: username
            label: spygar_shopify.credential.username
            required: true

    spygar-shopify-credentials-create-modal-password:
        module: pim/form/common/fields/password
        parent: spygar-shopify-credentials-create-modal
        position: 20
        targetZone: fields
        config:
            fieldName: password
            label: spygar_shopify.credential.password
            required: true

    spygar-shopify-credentials-create-modal-version:
        module: spygarmagento2/settings/common/version
        parent: spygar-shopify-credentials-create-modal
        position: 30
        targetZone: fields
        config:
            fieldName: version
            label: spygar_shopify.credential.version
            choices: ['2020-07', '2020-10', '2021-01','2021-04']
            isMultiple: false
            required: true
            defaultValue: []