services:
    spygar.shopify.connector.controller:
        public: true
        class: Spygar\Magento2\Controller\ShopifyController
        arguments:
            - "@spygar.shopify.connector.service"

    spygar.shopify.connector.credential.controller:
        public: true
        class: Spygar\Magento2\Controller\Rest\CredentialController
        arguments:
            - "@spygar.shopify.credential.repository"
            - "@doctrine.orm.entity_manager"
            - "@spygar.shopify.oauth_client.helper"

