services:
    spygar.shopify.connector.controller:
        public: true
        class: Spygar\Magento2\Controller\ShopifyController
        arguments:
            - "@spygar.magento2.connector.service"

    spygar.magento2.connector.credential.controller:
        public: true
        class: Spygar\Magento2\Controller\Rest\CredentialController
        arguments:
            - "@spygar.magento2.credential.repository"
            - "@doctrine.orm.entity_manager"
            - "@spygar.magento2.oauth_client.helper"

