parameters:

services:
    spygar.akeneo_shopify.form.provider.job_instance:
        public: true
        class: 'Akeneo\Platform\Bundle\ImportExportBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
                spygar_shopify_category_export: pim-job-instance-spygar-akeneo-shopify-category-export
        tags:
            - { name: pim_enrich.provider.form }