services:
    spygar_magento2.reader.database.category:
        class: Spygar\Magento2\Connector\Export\Reader\CategoryReader
        arguments:
            - '@pim_catalog.repository.category'
            - '@pim_catalog.repository.channel'            