services:
    spygar.magento2.credential.repository:
        public: true
        class: Spygar\Magento2\Repository\CredentialsRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - '@pim_catalog.repository.channel'
    
    spygar.magento2.data_mapping.repository:
        public: true
        class: Spygar\Magento2\Repository\DataMappingRepository
        arguments:
            - "@doctrine.orm.entity_manager"