services:
    spygar.magento2.credential.repository:
        public: true
        class: Spygar\Magento2\Repository\CredentialsRepository
        arguments:
            - "@doctrine.orm.entity_manager"