config:
    paths:
        spygarmagento2/controller/credentials: spygarmagento2/js/controller/credentials
        spygarmagento2/controller/mapping: spygarmagento2/js/controller/mapping
        spygarmagento2/controller/edit-credential: spygarmagento2/js/controller/edit-credential
        spygarmagento2/controller/documentation: spygarmagento2/js/controller/documentation
        # spygarmagento2/controller/api-connection: spygarmagento2/js/controller/api-connection
        

        # forms 
        spygarmagento2/settings/tabs/attribute-mapping: spygarmagento2/js/settings/tabs/attribute-mapping
        spygarmagento2/settings/tabs/mapping-configuration: spygarmagento2/js/settings/tabs/mapping-configuration
        spygarmagento2/settings/tabs/documentation: spygarmagento2/js/settings/tabs/documentation
        spygarmagento2/settings/tabs/stores: spygarmagento2/js/settings/tabs/stores
        # spygarmagento2/settings/tabs/api-connection: spygarmagento2/js/settings/tabs/api-connection
        
        # common
        spygarmagento2/settings/common/base-tab: spygarmagento2/js/settings/common/baseTab
        spygarmagento2/settings/common/version: spygarmagento2/js/settings/common/version
        spygarmagento2/settings/common/locale-mapping: spygarmagento2/js/settings/common/locale-mapping
        spygarmagento2/settings/common/credentials: spygarmagento2/js/settings/common/credentials
        spygarmagento2/settings/common/locales: spygarmagento2/js/settings/common/locales
        spygarmagento2/settings/common/scope: spygarmagento2/js/settings/common/scope
        # buttons
        spygarmagento2/settings/common/save: spygarmagento2/js/settings/common/save

        # fields
        spygarmagento2/settings/fields/text: spygarmagento2/js/settings/fields/text

        # ======================= Templates ===================================
        spygarmagento2/templates/credential/lists: spygarmagento2/templates/credential/credential-lists.html
        spygarmagento2/templates/credential/locale-mapping: spygarmagento2/templates/credential/locale-mapping.html
        spygarmagento2/templates/tab/mapping: spygarmagento2/templates/tab/mapping.html
        spygarmagento2/templates/tab/documentation: spygarmagento2/templates/tab/documentation.html
        spygarmagento2/templates/tab/stores: spygarmagento2/templates/tab/stores.html
        # spygarmagento2/templates/tab/api-connection: spygarmagento2/templates/tab/api-connection.html
        ## common templates
        spygarmagento2/templates/tab/locales: spygarmagento2/templates/common/locales.html
        spygarmagento2/templates/tab/scope: spygarmagento2/templates/common/scope.html

    config:
        # controllers     
        pim/controller-registry:
            controllers:  
             # akeneo api connection
                spygar_magento2_documentation:
                    module: spygarmagento2/controller/documentation

                # credential controller
                spygar_magento2_credentials:
                    module: spygarmagento2/controller/credentials

                # attribute mapping controller
                spygar_shopify_mapping:
                    module: spygarmagento2/controller/mapping

                # credential edit controller
                spygar_magento2_edit_credential:
                    module: spygarmagento2/controller/edit-credential

               
        # fetchers
        pim/fetcher-registry:
            fetchers:
                sylius-fields:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: spygar_shopify_get_fields
                shopify-credentials:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: spygar_shopify_get_credentials