services:
    spygar.magento2.connector.service:
        public: true
        class: Spygar\Magento2\Services\SpygarMagento2Service
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.magento2.credential.repository"

    spygar.magento2.oauth_client.helper:
        public: true
        class: Spygar\Magento2\Components\OAuthClientHelper
        arguments:
            - "@spygar.magento2.connector.service"
        
