services:
    spygar_magento2.category_export.step:
        class: Spygar\Magento2\Steps\BaseStep
        public: true
        arguments:
            - 'category_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@spygar_magento2.reader.database.category'
            - '@pim_connector.processor.normalization.category'
            - '@spygar_magento2.category.writer'
            - 10

    spygar_magento2.family_export.step:
        class: Spygar\Magento2\Steps\BaseStep
        public: true
        arguments:
            - 'category_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.family'
            - '@pim_connector.processor.normalization.family'
            - '@spygar_magento2.family.writer'
            - 10