services:
  spygar_magento2.category.writer:
    class: Spygar\Magento2\Connector\Export\Writer\CategoryWriter
    arguments:
        - "@spygar.magento2.connector.service"

  spygar_magento2.family.writer:
    class: Spygar\Magento2\Connector\Export\Writer\FamilyWriter
    arguments:
      - "@spygar.magento2.connector.service"