datagrid:
    spygar-magento2-credentials-grid:
        extended_entity_name: Spygar\Magento2\Entity\Credentials
        options:
            entityHint: credentials
            manageFilters: false
        source:
            # acl_resource: 
            type: pim_datasource_default
            repository_method: createDatagridQueryBuilder
            entity: 'Spygar\Magento2\Entity\Credentials'
            query:
                select:
                    - c.id
                    - c.url
                    - c.active
                from:
                    - { table: 'Spygar\Magento2\Entity\Credentials', alias: c }
        columns:
            id:
                label: spygar_magento2.credential.id
                frontend_type: label
            url:
                label: spygar_magento2.credential.url
                frontend_type: label
            active:
                label: spygar_magento2.credential.active
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
        sorters:
            columns:
                url:
                    data_name: c.url
                active:
                    data_name: c.active
            default:
                url: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                url:
                    type: search
                    data_name: c.url
                active:
                    type:      boolean
                    label:     Activated
                    data_name: c.active
        properties:
            id: ~
            edit_link:
                type: url
                route: spygar_magento2_edit_credential
                params:
                    - id
            toggle_link:
                type: url
                route: spygar_magento2_toggle_credential
                params:
                    - id
            delete_link:
                type: url
                route: spygar_magento2_delete_credential
                params:
                    - id
        actions:
            toggle:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--switch
                type:         navigate
                label:        Change status
                link:         toggle_link
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit
                link:      edit_link
                # acl_resource: spygar_connector_configuration
                rowAction: true
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         Delete
                link:          delete_link
            