extensions:
   # Akeneo Magento2 Menu
    pim-menu-spygar-magento2:
        module: pim/menu/tab
        parent: pim-menu
        position: 80
        targetZone: mainMenu
        config:
            title: pim_menu.tab.spygar_magento2
            iconModifier: iconSpygarMagento2Connector

    pim-menu-spygar-magento2-column:
        module: pim/menu/column
        parent: pim-menu
        position: 510
        targetZone: column
        config:
            stateCode: pim-menu-spygar-magento2
            tab: pim-menu-spygar-magento2
            navigationTitle: pim_menu.navigation.spygar_magento2

    pim-menu-spygar-magento2-navigation-block:
        module: pim/menu/navigation-block
        parent: pim-menu-spygar-magento2-column
        position: 60
        targetZone: navigation
        config:
            title: pim_menu.navigation.spygar_magento2
            
# side bar menus
    # docs
    pim-menu-spygar-magento2-documentation:
        module: pim/menu/item
        parent: pim-menu-spygar-magento2-navigation-block
        position: 90
        config:
            title: pim_menu.item.documentation
            to: spygar_magento2_documentation

    # credentials  
    pim-menu-spygar-magento2-credentials:
        module: pim/menu/item
        parent: pim-menu-spygar-magento2-navigation-block
        position: 100
        config:
            title: pim_menu.item.credentials
            to: spygar_magento2_credentials

    # Common Mapping  
    # pim-menu-spygar-magento2-configurations:
    #     module: pim/menu/item
    #     parent: pim-menu-spygar-magento2-navigation-block
    #     position: 110
    #     config:
    #         title: pim_menu.item.configurations
    #         to: spygar_magento2_configurations