extensions:
    spygar-magento2-credential-edit-form:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    spygar-magento2-credential-edit-form-grid-container:
        module: pim/common/simple-view
        parent: spygar-magento2-credential-edit-form
        targetZone: content
        config:
            template: pim/template/form/index/index

    spygar-magento2-credential-edit-form-user-navigation:
        module: pim/menu/user-navigation
        parent: spygar-magento2-credential-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

     # Save Button        
    spygar-magento2-credential-edit-form-save:
        module: spygarmagento2/settings/common/save
        parent: spygar-magento2-credential-edit-form
        targetZone: buttons
        position: 100
        config:
            updateSuccessMessage: spygar_magento2.credential.update_successful
            updateFailureMessage: spygar_magento2.credential.update_failed
            notReadyMessage: spygar_magento2.credential.field_not_ready
            url: spygar_magento2_update_credential

    spygar-magento2-credential-edit-form-grid-title:
        module: pim/common/grid-title
        parent: spygar-magento2-credential-edit-form
        targetZone: title
        config:
            title: pim_user_management.entity.user.page_title.index

    spygar-magento2-credential-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: spygar-magento2-credential-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-spygar-magento2
            item: pim-menu-spygar-magento2-credentials


    # tabs
    spygar-magento2-credential-edit-form-tabs:
        module: pim/form/common/form-tabs
        parent: spygar-magento2-credential-edit-form
        targetZone: content
        position: 90

    # credential tab
    spygar-magento2-credential-edit-form-credential-tab:
        module: spygarmagento2/settings/common/base-tab
        parent: spygar-magento2-credential-edit-form-tabs
        targetZone: container
        position: 100
        config:
            code: spygar_magento2.tab.credential
            label: spygar_magento2.tab.credential

    # credential store tab
    spygar-magento2-credential-edit-form-stores:
        module: spygarmagento2/settings/common/base-tab
        parent: spygar-magento2-credential-edit-form-tabs
        targetZone: container
        position: 110
        config:
            code: spygar_magento2.tab.stores
            label: spygar_magento2.tab.stores

    # credential attribute tab
    spygar-magento2-credential-edit-form-attribute-mapping:
        module: spygarmagento2/settings/common/base-tab
        parent: spygar-magento2-credential-edit-form-tabs
        targetZone: container
        position: 120
        config:
            code: spygar_magento2.tab.attribute_mapping
            label: spygar_magento2.tab.attribute_mapping
    
    # credential media tab
    spygar-magento2-credential-edit-form-media-mapping:
        module: spygarmagento2/settings/common/base-tab
        parent: spygar-magento2-credential-edit-form-tabs
        targetZone: container
        position: 120
        config:
            code: spygar_magento2.tab.media_mapping
            label: spygar_magento2.tab.media_mapping
    
    # credential tab properties
    spygar-magento2-credential-edit-url:
        module: spygarmagento2/settings/fields/text
        parent: spygar-magento2-credential-edit-form-credential-tab
        targetZone: self
        position: 120
        config:
            fieldName: url
            label: spygar_magento2.form.properties.url

    spygar-magento2-credential-edit-access_token:
        module: spygarmagento2/settings/fields/text
        parent: spygar-magento2-credential-edit-form-credential-tab
        targetZone: self
        position: 140
        config:
            fieldName: access_token
            label: spygar_magento2.form.properties.access_token

    # credential store tab properties
    spygar-magento2-credential-edit-store-mapping:
        module: spygarmagento2/settings/tabs/stores
        parent: spygar-magento2-credential-edit-form-stores
        targetZone: self
        position: 150
        config:
            title: spygar_magento2.stores
    
    # credential attribute mapping
    spygar-magento2-credential-edit-attribute-mapping:
        module: spygarmagento2/settings/tabs/attribute-mapping
        parent: spygar-magento2-credential-edit-form-attribute-mapping
        targetZone: self
        position: 160
        config:
            title: spygar_magento2.attribute_mapping

    # credential attribute mapping
    spygar-magento2-credential-media-mapping:
        module: spygarmagento2/settings/tabs/media
        parent: spygar-magento2-credential-edit-form-media-mapping
        targetZone: self
        position: 160
        config:
            title: spygar_magento2.attribute_mapping

            