extensions:
    spygar-magento2-documentation:
        module: oro/form/system/config

    spygar-magento2-documentation-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: spygar-magento2-documentation
        targetZone: breadcrumbs
        config:
            tab: pim-menu-spygar-magento2
            item: pim-menu-spygar-magento2-documentation

    spygar-magento2-documentation-title:
        module: pim/common/grid-title
        parent: spygar-magento2-documentation
        targetZone: title
        config:
            title: Documentation
            countable: false

    spygar-magento2-documentation-user-navigation:
        module: pim/menu/user-navigation
        parent: spygar-magento2-documentation
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    spygar-magento2-documentation-config-tabs:
        module: pim/form/common/form-tabs
        parent: spygar-magento2-documentation
        targetZone: content
        position: 100

    # spygar-magento2-documentation-config-save:
    #     module: oro/form/system/config/save
    #     parent: spygar-magento2-documentation
    #     targetZone: buttons
    #     position: 100

    spygar-magento2-documentation-config-tab-docs:
        module: spygarmagento2/settings/tabs/documentation
        parent: spygar-magento2-documentation-config-tabs
        targetZone: container
        position: 100

    # spygar-magento2-documentation-config-tab-notification:
    #     module: oro/form/system/config/tab/notification
    #     parent: spygar-magento2-documentation-config-tabs
    #     targetZone: container
    #     position: 110

    spygar-magento2-documentation-state:
        module: pim/form/common/state
        parent: spygar-magento2-documentation
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.label