extensions:
    spygar-magento2-credentials:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    spygar-magento2-credentials-grid-container:
        module: pim/common/simple-view
        parent: spygar-magento2-credentials
        targetZone: content
        config:
            template: pim/template/form/index/index

    spygar-magento2-credentials-user-navigation:
        module: pim/menu/user-navigation
        parent: spygar-magento2-credentials
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    spygar-magento2-credentials-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: spygar-magento2-credentials
        targetZone: breadcrumbs
        config:
            tab: pim-menu-spygar-magento2
            item: pim-menu-spygar-magento2-credentials

    spygar-magento2-credentials-filters-list:
        module: oro/datafilter/filters-list
        parent: spygar-magento2-credentials-grid-container
        targetZone: filters

    spygar-magento2-credentials-filters-manage:
        module: oro/datafilter/filters-button
        parent: spygar-magento2-credentials-grid-container
        targetZone: filters

    spygar-magento2-credentials-pagination:
        module: oro/datagrid/pagination-input
        parent: spygar-magento2-credentials-grid-container
        targetZone: toolbar
        config:
            gridName: spygar-magento2-credentials-grid

    spygar-magento2-credentials-grid:
        module: pim/form/common/index/grid
        parent: spygar-magento2-credentials-grid-container
        position: 1000
        config:
            alias: spygar-magento2-credentials-grid

    spygar-magento2-credentials-create-button:
        module: pim/form/common/index/create-button
        parent: spygar-magento2-credentials
        targetZone: buttons
        position: 100
        config:
           title: spygar_magento2.credential.create
           modalForm: spygar-magento2-credentials-create-modal