extensions:
    akeneo-shopify-credential-edit-form:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    akeneo-shopify-credential-edit-form-grid-container:
        module: pim/common/simple-view
        parent: akeneo-shopify-credential-edit-form
        targetZone: content
        config:
            template: pim/template/form/index/index

    akeneo-shopify-credential-edit-form-user-navigation:
        module: pim/menu/user-navigation
        parent: akeneo-shopify-credential-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

     # Save Button        
    akeneo-shopify-credential-edit-form-save:
        module: spygarmagento2/settings/common/save
        parent: akeneo-shopify-credential-edit-form
        targetZone: buttons
        position: 100
        config:
            updateSuccessMessage: spygar_shopify.credential.update_successful
            updateFailureMessage: spygar_shopify.credential.update_failed
            notReadyMessage: spygar_shopify.credential.field_not_ready
            url: spygar_shopify_create_credential

    akeneo-shopify-credential-edit-form-grid-title:
        module: pim/common/grid-title
        parent: akeneo-shopify-credential-edit-form
        targetZone: title
        config:
            title: pim_user_management.entity.user.page_title.index

    akeneo-shopify-credential-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: akeneo-shopify-credential-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-akeneo-shopify
            item: pim-menu-akeneo-shopify-credentials


    # tabs
    akeneo-shopify-credential-edit-form-tabs:
        module: pim/form/common/form-tabs
        parent: akeneo-shopify-credential-edit-form
        targetZone: content
        position: 90

    # credential tab
    akeneo-shopify-credential-edit-form-credential-tab:
        module: spygarmagento2/settings/common/base-tab
        parent: akeneo-shopify-credential-edit-form-tabs
        targetZone: container
        position: 100
        config:
            code: spygar_shopify.tab.credential
            label: spygar_shopify.tab.credential

    # credential locale tab
    # akeneo-shopify-credential-edit-form-locales:
    #     module: spygarmagento2/settings/common/base-tab
    #     parent: akeneo-shopify-credential-edit-form-tabs
    #     targetZone: container
    #     position: 110
    #     config:
    #         code: spygar_shopify.tab.locales
    #         label: spygar_shopify.tab.locales

    # credential locale tab
    akeneo-shopify-credential-edit-form-attribute-mapping:
        module: spygarmagento2/settings/common/base-tab
        parent: akeneo-shopify-credential-edit-form-tabs
        targetZone: container
        position: 120
        config:
            code: spygar_shopify.tab.attribute_mapping
            label: spygar_shopify.tab.attribute_mapping

    # credential tab properties
    akeneo-shopify-credential-edit-url:
        module: spygarmagento2/settings/fields/text
        parent: akeneo-shopify-credential-edit-form-credential-tab
        targetZone: self
        position: 120
        config:
            fieldName: url
            label: spygar_shopify.form.properties.url

    akeneo-shopify-credential-edit-username:
        module: spygarmagento2/settings/fields/text
        parent: akeneo-shopify-credential-edit-form-credential-tab
        targetZone: self
        position: 130
        config:
            fieldName: username
            label: spygar_shopify.form.properties.username

    
    akeneo-shopify-credential-edit-password:
        module: spygarmagento2/settings/fields/text
        parent: akeneo-shopify-credential-edit-form-credential-tab
        targetZone: self
        position: 140
        config:
            fieldName: password
            label: spygar_shopify.form.properties.password

    # spygar-shopify-credentials-create-modal-version:
    #     module: spygarmagento2/settings/common/version
    #     parent: spygar-shopify-credentials-create-modal
    #     position: 30
    #     targetZone: fields
    #     config:
    #         fieldName: version
    #         label: spygar_shopify.credential.version
    #         choices: ['2020-07', '2020-10', '2021-01','2021-04']
    #         isMultiple: false
    #         required: true
    #         defaultValue: []

            
    # credential locale tab properties
    # akeneo-shopify-credential-edit-locale-mapping:
    #     module: spygarmagento2/settings/common/locale-mapping
    #     parent: akeneo-shopify-credential-edit-form-locales
    #     targetZone: self
    #     position: 150
    #     config:
    #         title: spygar_shopify.locale

    akeneo-shopify-credential-edit-attribute-mapping:
        module: spygarmagento2/settings/tabs/attribute-mapping
        parent: akeneo-shopify-credential-edit-form-attribute-mapping
        targetZone: self
        position: 160
        config:
            title: spygar_shopify.attribute_mapping

            