extensions:
    spygar-shopify-credentials-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    spygar-shopify-credentials-index-grid-container:
        module: pim/common/simple-view
        parent: spygar-shopify-credentials-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    spygar-shopify-credentials-index-user-navigation:
        module: pim/menu/user-navigation
        parent: spygar-shopify-credentials-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    spygar-shopify-credentials-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: spygar-shopify-credentials-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-spygar-shopify
            item: pim-menu-spygar-shopify-credentials

    spygar-shopify-credentials-index-filters-list:
        module: oro/datafilter/filters-list
        parent: spygar-shopify-credentials-index-grid-container
        targetZone: filters

    spygar-shopify-credentials-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: spygar-shopify-credentials-index-grid-container
        targetZone: filters

    spygar-shopify-credentials-index-pagination:
        module: oro/datagrid/pagination-input
        parent: spygar-shopify-credentials-index-grid-container
        targetZone: toolbar
        config:
            gridName: spygar-shopify-credentials-grid

    spygar-shopify-credentials-index-grid:
        module: pim/form/common/index/grid
        parent: spygar-shopify-credentials-index-grid-container
        position: 1000
        config:
            alias: spygar-shopify-credentials-grid

    spygar-shopify-credentials-index-create-button:
        module: pim/form/common/index/create-button
        parent: spygar-shopify-credentials-index
        targetZone: buttons
        position: 100
        config:
           title: spygar_shopify.credential.create
           modalForm: spygar-shopify-credentials-create-modal