Spygar\Magento2\Entity\Credentials:
    type: entity
    table: spygar_magento2_credentials
    repositoryClass: Spygar\Magento2\Repository\CredentialsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        apiKey:
            type: string
            length: 255
        password:
            type: string
            length: 255
        version:
            type: string
            length: 50
        active:
            type: boolean
            options:
                default: 0
        defaultSet:
            type: boolean
            options:
                default: 0
        resources:
            type: text
            nullable: true
        extras:
            type: string
            length: 255
            nullable: true
       
    lifecycleCallbacks: {  }
