Spygar\Magento2\Entity\Credentials:
    type: entity
    table: spygar_magento2_credentials
    repositoryClass: Spygar\Magento2\Repository\CredentialsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        accessToken:
            type: string
            length: 255
        active:
            type: boolean
            options:
                default: 0
        defaultSet:
            type: boolean
            options:
                default: 0
        resources:
            type: json
            nullable: true
        extras:
            type: json
            nullable: true
       
    lifecycleCallbacks: {  }
