<?php

namespace Spygar\Magento2\Repository;

/**
 * DataMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataMappingRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct()
    {
        
    }
}
