extensions:
    pim-job-instance-spygar-akeneo-magento2-category-export-edit:
        module: pim/form/common/edit-form

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-main-image:
        module: pim/form/common/main-image
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: main-image
        config:
            path: bundles/spygarmagento2/images/akeneo-magento2.png

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        position: 1000

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: content
        position: 100

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 120
        config:
            tabTitle: pim_common.properties
            tabCode: pim-job-instance-properties

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-settings:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-tabs
        targetZone: container
        # aclResourceId: pim_importexport_export_profile_history
        position: 130
        config:
            tabTitle: pim_common.settings
            tabCode: pim-job-instance-settings

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-history:
        module: pim/common/tab/history
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 140
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_common.history
            tabCode: pim-job-instance-history

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties-credential:
        module: spygarmagento2/settings/common/credentials
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties
        targetZone: properties
        position: 90
        config:
            fieldCode: credential
            label: pim_common.credential

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_common.code
            readOnly: true

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_common.label
            readOnly: false

    # setting properties.
    pim-job-instance-spygar-akeneo-magento2-category-export-edit-scope:
        module: spygarmagento2/settings/common/scope
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-settings
        targetZone: properties
        position: 90

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-locales:
        module: spygarmagento2/settings/common/locales
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-settings
        targetZone: properties
        position: 100

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: title
        position: 100

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: meta
        position: 100

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: buttons
        position: 50

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.export_profile
                subTitle: pim_menu.item.export_profile
                content: pim_common.confirm_deletion
                success: pim_import_export.entity.job_instance.flash.delete.success
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: buttons
        position: 120

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pim-job-instance-spygar-akeneo-magento2-category-export-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_import_export.entity.job_instance.label

    # pim-job-instance-spygar-akeneo-magento2-category-export-edit-validation:
    #     module: pim/job/common/edit/validation
    #     parent: pim-job-instance-spygar-akeneo-magento2-category-export-edit
